// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxEoO-P57MygbRKAf-TL4el0ytfpXgtwc',
    appId: '1:1094437880141:web:6fce31e27faadd3a98f704',
    messagingSenderId: '1094437880141',
    projectId: 'fasal-9d1fb',
    authDomain: 'fasal-9d1fb.firebaseapp.com',
    storageBucket: 'fasal-9d1fb.appspot.com',
    measurementId: 'G-222Z9F0SJC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApDkJ1K1TaYWo408lu-6R-35OZNUWgsMs',
    appId: '1:1094437880141:android:d3f65405600241b498f704',
    messagingSenderId: '1094437880141',
    projectId: 'fasal-9d1fb',
    storageBucket: 'fasal-9d1fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmpHlhmH_Gq5Y9jqcB8v8ypKjlmswVnFg',
    appId: '1:1094437880141:ios:dd703a6d4335c07798f704',
    messagingSenderId: '1094437880141',
    projectId: 'fasal-9d1fb',
    storageBucket: 'fasal-9d1fb.appspot.com',
    iosBundleId: 'com.example.fasal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmpHlhmH_Gq5Y9jqcB8v8ypKjlmswVnFg',
    appId: '1:1094437880141:ios:dd703a6d4335c07798f704',
    messagingSenderId: '1094437880141',
    projectId: 'fasal-9d1fb',
    storageBucket: 'fasal-9d1fb.appspot.com',
    iosBundleId: 'com.example.fasal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxEoO-P57MygbRKAf-TL4el0ytfpXgtwc',
    appId: '1:1094437880141:web:f15a0f1effa9d66f98f704',
    messagingSenderId: '1094437880141',
    projectId: 'fasal-9d1fb',
    authDomain: 'fasal-9d1fb.firebaseapp.com',
    storageBucket: 'fasal-9d1fb.appspot.com',
    measurementId: 'G-1417JTS9RG',
  );
}
